# Generated by Django 5.0 on 2023-12-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_user_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='users',
            new_name='user',
        ),
    ]
