# Generated by Django 5.0 on 2024-01-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_users_conversation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='User',
        ),
    ]
